-- 코드를 작성해주세요
SELECT COUNT(ID) AS COUNT
FROM ECOLI_DATA
-- WHERE BINARY(GENOTYPE) NOT LIKE '%1_' (BINARY(GENOTYPE) REGEXP ('%1'|'%1__'));
WHERE (GENOTYPE & 2 = 0) AND (GENOTYPE & 1 = 1 OR GENOTYPE & 4 = 4)